routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
Route::get('/', 'MainController@index')->name('index');
Route::get('project_details/{id}', 'ProjectController@project_details')->name('project_details');
Route::get('about', 'AboutController@about')->name('about');
Route::get('about/{id}','AboutController@singleteam')->name('singleteam');
Route::get('projects', 'ProjectController@projects')->name('projects');
Route::get('/services', 'ServiceController@services')->name('services');
Route::get('/service/{id}', 'ServiceController@singleservice')->name('single.service');
Route::get('/service/{type}/{id}', 'ServiceController@subService')->name('single.service-type');
Route::get('/cost','CostController@cost')->name('cost');
Route::get('contact', 'MainController@contact')->name('contact');
Route::post('/contact/send', 'MainController@send')->name('contact.send');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Project extends Model
{
    //
    public $table = 'projects';

    protected  $guarded = [];

    // protected $casts = [
    //     "date" => "datetime"
    // ];

    public function project()
    {
       return $this->get();
    }

    public function projectlist()
    {
        return $this->belongsTo(Projectlist::class);
    }


    public function getFormattedDateAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['date'])->format(" d M Y");
    
    }
}

resources/views/about.blade.php
@extends('layouts.layout')
@section('content')
<!-- subheader -->
<section id="subheader" style="background: url({{asset('/storage/'.$data['aboutbanner'][0]->image) }}) " data-speed="8" data-type="background" class="text-light">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{$data['aboutbanner'][0]->title}}</h1>
                <ul class="crumb">
                    <li><a href="/">Home</a></li>
                    <li class="sep">/</li>
                    <li>About Us</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- subheader close -->
<!-- content begin -->
<div id="content" class="no-top no-bottom">

    @foreach($data['about'] as $about)

    <section id="section-about-us-2"  class="side-bg no-padding">

        <div class="image-container col-md-5  pull-right " style="background: url({{asset("/storage/".$about->image)}});@if(($loop->index + 1 ) %2==0) right:0 @endif " data-delay="0">

        </div>

        <div class="container">
            <div class="row">
                <div class="inner-padding">
                    <div class="col-md-6 @if(($loop->index + 1 ) %2 != 0) col-md-offset-6 @endif wow fadeInRight" data-wow-delay=".5s">

                        <h2>{{$about->title}}</h2>

                        <p class="intro">{{$about->heading}}</p>

                         <p>{{$about->description}}</p>

                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </section>
@endforeach
<!--team -->

    <section id="section-team">
        <div class="container">
            <div class="row">
                <div class="col-md-12 container-4">
                    @foreach($data['team'] as $team)
                    <!-- team member -->
                    <div class="de-team-list">
                        <div class="team-pic">

                            <img src="/storage/{{$team->image}}" class="img-responsive" alt="" />

                        </div>
                        <div class="team-desc col-md-12">
                            <a class="simple-ajax-popup-align-top" href="{{route('singleteam',$team->id)}}" style="text-decoration : none">
                            <h3>{{$team->name}}</h3>

                            <p class="lead">{{$team->post}}</p>

                            <div class="small-border"></div>
                            <p>{{$team->shortdescription}}</p>

                            <div class="social">
                                <a href="#"><i class="fa fa-phone fa-lg"></i>&nbsp;</a>{{$team->phone}}
                                <br/>
                                <a href="mailto:{{$team->email}}"><i class="fa fa-envelope fa-lg"></i>&nbsp;</a>{{$team->email}}
                                <br>
                            </div>
                                <div class="social text-center" style="margin-top: 10%;">
                                    @if($team->facebook)
                                    <a href="{{$team->facebook}}"  target="_blank"><i class="fa fa-facebook fa-lg" style="padding: 10px"></i></a>
                                    @endif
{{--                                    <a href="www."><i class="fa fa-google-plus fa-lg" style="padding: 10px"></i></a>--}}
                                        @if($team->instagram)
                                    <a href="https://www.instagram.com" target="_blank"><i class="fa fa-instagram fa-lg" style="padding: 10px"></i></a>
                                        @endif
{{--                                    <a href="index-arts.html#"><i class="fa fa-twitter fa-lg" style="padding: 10px"></i></a>--}}
                                </div>
                            </a>
                        </div>
                    </div>
                    <!-- team close -->
                    @endforeach
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </section>



    <!-- section begin -->
    <section id="view-all-projects" class="call-to-action bg-color dark text-center" data-speed="5" data-type="background" aria-label="view-all-projects">
        <a href="contact" class="btn btn-line-black btn-big">Talk With Us</a>
    </section>
    <!-- logo carousel section close -->
</div>

@endsection

resources/views/contact.blade.php
@extends('layouts.layout')
@section('content')
<!-- subheader -->
<section id="subheader" data-speed="8" data-type="background">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Contact</h1>
                <ul class="crumb">
                    <li><a href="/">Home</a></li>
                    <li class="sep">/</li>
                    <li>Contact</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- content begin -->
<div id="content" class="no-top">
    <section class="no-top" aria-label="map-container">
        <div id="map"></div>
    </section>

    <div class="container">
        <div class="row">
            <div class="col-md-8">

                <h3>Send Us Message</h3>
                <div id='mail_success' class='success'>Your message has been sent successfully.</div>
                <div id='mail_fail' class='error'>Sorry, error occured this time sending your message.</div>
                <form name="contactForm" id='contact_form'  action='{{route('contact.send')}}' method="post">
                    @csrf
                    <div class="row">

                        <div class="col-md-4">

                            <div id='name_error' class='error'>Please enter your name.</div>
                            <div>

                                <input type='text' name='name' id='name' class="form-control" placeholder="Your Name">
                            </div>

                            <div id='email_error' class='error'>Please enter your valid E-mail ID.</div>
                            <div>
                                <input type='text' name='email' id='email' class="form-control" placeholder="Your Email">
                            </div>

                            <div id='phone_error' class='error'>Please enter your phone number.</div>
                            <div>
                                <input type='text' name='phone' id='phone' class="form-control" placeholder="Your Phone">
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div id='message_error' class='error'>Please enter your message.</div>
                            <div>
                                <textarea name='message' id='message' class="form-control" placeholder="Your Message"></textarea>
                            </div>
                        </div>

                        <div class="col-md-12">
{{--                            <p id='submit'>--}}
{{--                                <input type='submit' id='send_message' value='Submit Form' class="btn btn-line">--}}
{{--                            </p>--}}
                            <button id='submit' type="submit" class="btn btn-line">Submit</button>

                        </div>
                    </div>
                </form>
            </div>

            <div id="sidebar" class="col-md-4">

                <div class="widget widget_text">
                    <h3>Contact Info</h3>
                    <address>
                        <span>{{$data['info']->company_address}}</span>
                        <span><strong>Phone:</strong>{{$data['info']->phone}}</span>
                        <span><strong>Email:</strong><a href="mailto:contact@example.com">{{$data['info']->email}}</a></span>
                        <span><strong>Web:</strong><a href="contact.html#test">{{$data['info']->web}}</a></span>
                        <span><strong>Open</strong>{{$data['info']->phone}}</span>
                    </address>
                </div>

            </div>
        </div>
    </div>
</div>


<script src="https://maps.googleapis.com/maps/api/js?language=en&key=AIzaSyAd1iF0qOMcbvehRChx4F1PxaB2MZPsUHc"></script>
<script src="{{asset('badger_assets/js/map.js')}}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script>
       $('#contact_form').on('submit',function(e){
           e.preventDefault();
           var url = $(this).attr('action');
           var name = $("#name").val();
           var email = $("#email").val();
           var phone = $("#phone").val();
           var message = $("#message").val();

           console.log(url);
           $.ajax({
               method: "POST",
               url: $(this).attr('action'),
               data:{
                      _token:'{{csrf_token()}}',
                      name:name,
                      email:email,
                      phone:phone,
                      message:message
               },
               success: function(data){
                    $('#mail_success').show();
                    setTimeout(()=>{
                        $('#mail_success').hide();
                   },5000);
                    console.log(data);
               },
               error:function (data) {
                    $('#mail_fail').show();
                    setTimeout(()=>{
                        $('#mail_fail').hide();
                    },5000);
               }
           })
       });
    </script>
@endsection

resources/views/cost.blade.php
@extends('layouts.layout')
@section('content')
    <!-- subheader -->
    <section id="subheader" data-speed="8" data-type="background">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Cost</h1>
                    <ul class="crumb">
                        <li><a href="/">Home</a></li>
                        <li class="sep">/</li>
                        <li>Cost</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
<div id="content">

    <div class="container">
        <div class="row">

            <div class="col-md-8">
                <h2>Cost Calculation</h2>
                <form name="contactForm" id='contact_form'  action='' method="">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div id='name_error' class='error'>Please enter Anna </div>
                            <div>
                                <label for="">Anna</label>
                                <input type='text' name='anna' id='anna' class="form-control" placeholder="Anna">
                            </div>

                            <div id='email_error' class='error'>Please enter your valid E-mail ID.</div>
                            <div>
                                <label for="">Square Feet</label>
                                <input type='text' name='square' id='square' class="form-control" placeholder="Square Feet">
                            </div>

                            <div id='phone_error' class='error'>Please enter your phone number.</div>
                            <div>
                                <label for="">Total Cost</label>
                                <input type='text' name='phone' id='phone' class="form-control" placeholder="">
                            </div>
                        </div>
                        <div class="col-md-12">
                            {{--                            <p id='submit'>--}}
                            {{--                                <input type='submit' id='send_message' value='Submit Form' class="btn btn-line">--}}
                            {{--                            </p>--}}
                            <button type="submit" id="submit" class="btn btn-line">Calculate</button>
                        </div>
                    </div>
                </form>
            </div>

            <div id="sidebar" class="col-md-4">

                <div class="widget widget_text">
                    <h3>Contact Info</h3>
                    <address>
                        <span>{{$data['info']->company_address}}</span>
                        <span><strong>Phone:</strong>{{$data['info']->phone}}</span>
{{--                        <span><strong>Fax:</strong>{{$data['info']->fax}}</span>--}}
                        <span><strong>Email:</strong><a href="mailto:contact@example.com">{{$data['info']->email}}</a></span>
                        <span><strong>Web:</strong><a href="contact.html#test">{{$data['info']->web}}</a></span>
                        <span><strong>Open</strong>{{$data['info']->phone}}</span>
                    </address>
                </div>

            </div>
        </div>
    </div>
</div>


</div>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script>
        $(document).ready(function () {
            $('#submit').click(function (event) {
                event.preventDefault();
                var anna = $('#anna').val();
                var square = $('#square').val();
                if(anna.length && square.length > 0){
                    var answer = parseInt(anna) + (parseInt(square)/342.25) * 100000;
                }
                $('#phone').val(answer.toFixed(2));

            });//end click
            $("#phone").prop("disabled", true);

            //Disable the submit button initially
            $("#submit").prop("disabled", true);
            //


            var annaSize = 0;
            var sqFeet = 0;
            var submitButton = $("#submit");
            //While the value is passed on anna
          $('#anna').on('keyup keypress blur', function(event){
              annaSize = $(this).val().length;
              submitButton.prop("disabled", true);
              if(sqFeet && annaSize){
                  submitButton.prop("disabled", false);
              }
              //this.value = this.value.replace(/[^0-9\.]/g,'');
              $(this).val($(this).val().replace(/[^0-9\.]/g,''));
              if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
                  event.preventDefault();
              }
          });

          $('#square').on('keyup keypress blur', function(event){
              sqFeet = $(this).val().length;
              submitButton.prop("disabled", true);
              if(sqFeet && annaSize){
                  submitButton.prop("disabled", false);
              }
              //this.value = this.value.replace(/[^0-9\.]/g,'');
              $(this).val($(this).val().replace(/[^0-9\.]/g,''));
              if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
                  event.preventDefault();
              }
          });

        });

    </script>
@endsection

resources/views/index.blade.php
@extends('layouts.layout')
@section('content')
<div id="content" class="no-bottom no-top">
{{--    {{dd(asset('/storage/'.$data['hire'][0]->image))}}--}}
<!-- revolution slider begin -->
<section id="section-welcome-13" style="background: url({{asset('/storage/'.$data['hire'][0]->image) }}) bottom right fixed" data-speed="3" data-type="background">

    <div class="center-y">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="spacer-double"></div>
                    @foreach($data['hire'] as $hire)
                        <h2 class="style-3">{{$hire->title1}}<strong class="id-color">&amp;</strong> {{$hire->title2}}</h2>
                        <div class="spacer-half"></div>
                        <p class="lead">{{$hire->description}} </p>
                    @endforeach
                    <div class="spacer-single"></div>
                    <a href="contact" class="btn btn-line-black btn-big scroll-to">Hire Us Now</a>
                    <div class="spacer-double"></div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- revolution slider close -->

<!-- section begin -->
<section id="section-no-bg">
    <div class="container">
        <div class="row table">

            <div class="col-md-6 table-cell">
                <img src="{{asset('storage/'.$data['about'][0]->image)}}" alt="" class="img-responsive wow fadeInUp" data-wow-duration="1.5s">
            </div>

            <div class="col-md-6 table-cell wow fadeInUp">
                <h2>{{$data['about'][0]->title}}</h2>

                <p class="lead">{{$data['about'][0]->heading}}</p>

                <p>{{\Illuminate\Support\Str::limit($data['about'][0]->description,100) }}</p>
                <a href="about" class="btn-custom">Read more</a>
                <div class="spacer-single"></div>
            </div>

            <div class="clearfix"></div>
        </div>
    </div>
</section>
<!-- section close -->

<!-- section begin -->
<section id="section-services" class="no-top no-bottom">
    <div class="container">
        <div class="row">
            @foreach($data["services"]->slice(0,3) as $service)
            <div class="col-md-4 text-middle text-light wow fadeInRight" data-wow-delay="0">
                <div class="shadow-soft" data-bgimage="url(images/services/t1.jpg)">
                    <div class="padding40 overlay40">
                        <h3>{{$service->service_title}}</h3>
                        <p>{{Illuminate\Support\Str::limit($service->service_desc,250)}}</p>
                        <a href="{{route('single.service',$service->id)}}" class="btn-line btn-fullwidth">Service Details</a>
                    </div>
                </div>
            </div>
            @endforeach


        </div>
    </div>
</section>
<!-- section close -->

<section id="section-why-choose-us-2">

    <div class="container">
        <div class="row">

            <div class="row">
                @foreach($data['extra'] as $extra)
                <div class="col-md-4 wow fadeInUp" data-wow-delay="{{$extra->delay1}}">
                    <div class="box-icon">
                        <span class="icon wow fadeIn" data-wow-delay="{{$extra->delay2}}"><i class="id-color icon-{{$extra->icon}}"></i></span>
                        <div class="text">
                            <h3>{{$extra->title}}</h3>
                            <p>{{$extra->description}}</p>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>

        </div>
    </div>
</section>
<!-- section close -->
    <section id="" style="background: url({{asset('/storage/'.$data['testinomal'][0]->image)}})" data-speed="3" data-type="background" class="text-light">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center wow fadeInUp">
                    <h1>{{$data['testinomal'][0]->title}}</h1>
                    <div class="separator"><span><i class="fa fa-circle"></i></span></div>
                    <div class="spacer-single"></div>
                </div>
            </div>
            <div id="testimonial-carousel" class="de_carousel  wow fadeInUp" data-wow-delay=".3s">
                @foreach($data['customer'] as $customer)
                    <div class="col-md-6 item">
                        <div class="de_testi">
                            <blockquote>
                                <p>{{$customer->description}}</p>
                                <div class="de_testi_by">
                                    {{$customer->name}}, Customer
                                </div>
                            </blockquote>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
<!-- section begin -->
<section id="view-all-projects" class="call-to-action text-light padding20" data-speed="5" data-type="background" aria-label="cta" data-bgcolor="#3562a8">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>Are you ready to makeover your home? </h2>
            </div>

            <div class="col-md-4 text-right">
                <a href="contact" class="btn btn-line btn-big mt20 wow fadeInUp">Get Quotation</a>
            </div>
        </div>
    </div>
</section>
<!-- logo carousel section close -->
</div>
@endsection

resources/views/project_details.blade.php
<div class="container project-view">

	<div class="row">
        <div class="col-md-8 project-images">
            @if($projectdetail->url == null)
            <img src="{{asset('storage/'.$projectdetail->image1)}}" alt="" class="img-responsive" />
            <img src="{{asset('storage/'.$projectdetail->image2)}}" alt="" class="img-responsive" />
            <img src="{{asset('storage/'.$projectdetail->image3)}}" alt="" class="img-responsive" />
            @else
            <iframe width="100%" height="500px" src="{{ $projectdetail->url }}" frameborder="0" allowfullscreen>
            </iframe>
            <img src="{{asset('storage/'.$projectdetail->image1)}}" alt="" class="img-responsive" />
            <img src="{{asset('storage/'.$projectdetail->image2)}}" alt="" class="img-responsive" />
            <img src="{{asset('storage/'.$projectdetail->image3)}}" alt="" class="img-responsive" />
            @endif
        </div>
        <div class="col-md-4">
            <div class="project-info">
                <h2>{{$projectdetail->title}}</h2>
                <div class="details">
                    <div class="info-text">
                        <span class="title">Date</span>
                        <span class="val">{{$projectdetail->formatted_date}}</span>
                    </div>

                    <div class="info-text">
                        <span class="title">Location</span>

                        <span class="val">{{$projectdetail->location}}</span>
                    </div>

                    <div class="info-text">
                        <span class="title">Client</span>
                        <span class="val">{{$projectdetail->client}}</span>
                    </div>

                    <div class="info-text">
                        <span class="title">Category</span>
                        <span class="val">{{$projectdetail->projectlist['title']}}</span>
                    </div>
                </div>
                <h4>Description</h4>
                <p>{{$projectdetail->description}}</p>
            </div>
        </div>
    </div>
</div>

resources/views/projects.blade.php
@extends('layouts.layout')
@section('content')
    <!-- subheader -->
{{--    {{dd(asset('storage/images/'.$data['projectbanner'][0]->image))}}--}}
    <section id="subheader" style="background: url({{asset('storage/'.$data['projectbanner'][0]->image)}})" data-speed="8" data-type="background" class="text-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Projects</h1>
                    <ul class="crumb">
                        <li><a href="/">Home</a></li>
                        <li class="sep">/</li>
                        <li>Projects</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- subheader close -->

    <div id="content">
        <div class="container">

            <div class="spacer-single"></div>

            <!-- portfolio filter begin -->
            <div class="row">
                <div class="col-md-12">

                    <ul id="filters" class="wow fadeInUp" data-wow-delay="0s">
                        @foreach($data['projectlist'] as $list)
                            <li><a href="project-contained-4-cols.html#"
                                   data-filter=".{{$list->title}}">{{$list->title}}</a></li>
                            @if($loop->last)
                                <li class="pull-right">
                                    <a href="project-contained-4-cols.html#" data-filter="*"
                                       class="selected">All Projects</a>
                                </li>
                            @endif
                        @endforeach
                    </ul>

                </div>
            </div>
            <!-- portfolio filter close -->

            <div id="gallery" class="row gallery full-gallery de-gallery pf_4_cols wow fadeInUp" data-wow-delay=".3s">

                <!-- gallery item -->


                @foreach($data['projects'] as $project)

                    <div class="col-md-3 col-sm-6 col-xs-12 item mb30 {{ $project->projectlist->title }}">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="{{route('project_details',$project->id)}}">
                        <span class="overlay">
                            <span class="pf_text">
                                <span class="project-name">{{$project->title}}</span>
                            </span>
                        </span>
                            </a>
                            <img src="{{asset('storage/'.$project->image1)}}" alt=""/>
                        </div>
                    </div>
            @endforeach

            <!-- close gallery item -->

                <!-- close gallery item -->

            </div>
        </div>
    </div>
    <section id="view-all-projects" class="call-to-action bg-color text-center" data-speed="5" data-type="background"
             aria-label="view-all-projects">
        <a href="contact" class="btn btn-line-black btn-big">Get Quotation</a>
    </section>

@endsection

resources/views/services.blade.php
@extends('layouts.layout')
@section('content')
<!-- subheader -->
}
<section id="subheader" style="background: url({{asset('storage/'.($data['servicebanner'][0]->image))}}" data-speed="8" data-type="background">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{$data['servicebanner'][0]->title}}</h1>
                <ul class="crumb">
                    <li><a href="/">Home</a></li>
                    <li class="sep">/</li>
                    <li>Services</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- subheader close -->
<div id="content">
    <div class="container">
        <div class="row">
            @foreach($data['services'] as $service)

            <div class="col-md-3">
                <h3><span class="id-color">{{$service->service_title}}</span> {{$service->title}}</h3>
                    {{Illuminate\Support\Str::limit($service->service_desc,250)}}
                <div class="spacer-single"></div>
                <img src="{{asset('storage/'.$service->image1)}}" class="img-responsive" alt="">
                <div class="spacer-single"></div>
                <a href="{{route('single.service',$service->id)}}" class="btn-line btn-fullwidth">Read More</a>
            </div>
                @endforeach

        </div>
    </div>



</div>
<section id="view-all-projects" class="call-to-action bg-color text-center" data-speed="5" data-type="background" aria-label="view-all-projects">
    <a href="contact" class="btn btn-line-black btn-big">Get Quotation</a>
</section>

@endsection

resources/views/singleteam.blade.php
<div class="container project-view">

    <div class="row">
        <div class="col-md-8 project-images" style="width: 60%">
            <img src="{{asset('storage/'.$team->image)}}" alt="" class="img-responsive" width="60%"/>
        </div>
        <div class="col-md-4">
            <div class="project-info">
                <h2>{{$team->name}}</h2>
                <div class="details">
                    <div class="info-text">
                        <span class="title">Post</span>
                        <span class="val">{{$team->post}}</span>
                    </div>

                    <div class="info-text">
                        <span class="title">Email</span>

                        <span class="val">{{$team->email}}</span>
                    </div>

                    <div class="info-text">
                        <span class="title">Phone</span>
                        <span class="val">{{$team->phone}}</span>
                    </div>

                </div>
                <p>{{$team->description}}</p>

{{--                <p>--}}
{{--                <h4>Our Solutions</h4>--}}
{{--                {{$projectdetail->solution}}--}}
{{--                </p>--}}
{{--                </p>--}}


            </div>
        </div>
    </div>
</div>

resources/views/template.blade.php
<div>
    <p>hi, this is {{$order['name']}}</p>
    <p>my email is {{$order['email']}}</p>
    <p>My phone number is {{$order['phone']}}</p>
    <p>my message is {{$order['message']}}</p>
</div>